#PROGRAM KASIR By SAS
echo "Masukkan nama pembeli: ";
read nama;
echo " ";
echo "PROGRAM KASIR by SAS";
echo "======================================";
echo "Kode Barang	|	Harga ";
echo "1. Roti Enak	|	Rp.5000";
echo "2. Aqua BkanVit	|	Rp.2500";
echo "3. Jus Fix Buah	|	Rp.7000";
echo "4. Susu Marni	|	Rp.10000";
echo "5. Mie Anak Kos	|	Rp.1500";
echo "======================================";
echo "Masukkan Kode Barang: ";
read kode;
echo " ";
case $kode in
1 ) barang='Roti Enak';
let harga=5000;
;;
2 ) barang='Aqua BkanVit';
let harga=2500;
;;
3 ) barang='Jus Fix Buah';
let harga=7000;
;;
4 ) barang='Susu Marni';
let harga=10000;
;;
5 ) barang='Mie Anak Kos';
let harga=1500;
;;
*) echo "$Pilihannya kan dari 1-6 BRO!!";
;;
esac
echo "Detail:";
echo "Nama Barang : $barang";
echo "Harga Barang : $harga";
echo "Banyaknya Barang : ";
read banyak;
let total=harga*banyak;
echo "================================================== ";
echo "Total yang Harus Dibayar : $total";
echo "Uang Pembayaran : ";
read bayar;
let kembalian=bayar-total;
echo "================================================== ";
echo "Kembalian Anda : $kembalian";
echo " ";
echo "Terimakasih Bp/Ibu $nama atas kepercayaannya";
echo "Sampai Berbelanja Kembali"; 